export const ALL_CATEGORIES = [
  { name: "Action", slug: "action" },
  { name: "Adventure", slug: "adventure" },
  { name: "Anime", slug: "anime" },
  { name: "Chuyển Sinh", slug: "chuyen-sinh" },
  { name: "Comedy", slug: "comedy" },
  { name: "Comic", slug: "comic" },
  { name: "Cổ Đại", slug: "co-dai" },
  { name: "Drama", slug: "drama" },
  { name: "Fantasy", slug: "fantasy" },
  { name: "Harem", slug: "harem" },
  { name: "Lịch sử", slug: "historical" },
  { name: "Kinh dị", slug: "horror" },
  { name: "Manhua", slug: "manhua" },
  { name: "Manhwa", slug: "manhwa" },
  { name: "Võ thuật", slug: "martial-arts" },
  { name: "Huyền huyễn", slug: "supernatural" },
  { name: "Ngôn Tình", slug: "ngon-tinh" },
  { name: "Lãng mạn", slug: "romance" },
  { name: "Học đường", slug: "school-life" },
  { name: "Sci-fi", slug: "sci-fi" },
  { name: "Shounen", slug: "shounen" },
  { name: "Thể thao", slug: "sports" },
  { name: "Trinh Thám", slug: "trinh-tham" },
  { name: "Webtoon", slug: "webtoon" },
  { name: "Xuyên Không", slug: "xuyen-khong" },
];